### ISSUE TITLE
Presentation accessibility

### ISSUE THREAD

**Issue by Lextuga007** [CDU-data-science-team/presentations#6]
From GSS guidance we should publish using html where possible, but Powerpoint presentations don't publish too well in GitHub so are often converted to pdf format. Is there any way can also publish to html or would that require a full recoding into xaringan slides? Is it worth doing that for the existing presentations we have in pdf?

**Comment by ChrisBeeley** [comment]
Do it online? https://www.pdftohtml.net/

We are not publishing documents for a mass audience, so we don't need to beat ourselves up about this

**Comment by Lextuga007** [comment]
I converted them :) There was only 2.
